.TH GANGLIA-NAGIOS-BRIDGE 8
.SH NAME
ganglia-nagios-bridge \- transfer Ganglia metrics to Nagios
.SH SYNOPSIS
.B ganglia-nagios-bridge
[\fBconfig-file\fR]
.SH DESCRIPTION
.B ganglia-nagios-bridge
extracts metrics from Ganglia XML and generates Nagios check results.
.SH OPTIONS
.TP
.BR config-file
Use a custom configuration file instead of the default.
